# NumPy
---
### The fundamental package for numerical computing in Python.

![numpy](./img/numpy.png)

#### It provides support for large, multi-dimensional arrays and matrices, along with a variety of mathematical functions, making it essential for scientific computing, data analysis, and machine learning applications. NumPy's efficient array operations and broadcasting capabilities simplify complex computations and enhance overall computational performance.

In [1]:
# Importing NumPy library
import numpy as np

# Creating a NumPy array
array = np.array([1, 2, 3, 4, 5])

array

array([1, 2, 3, 4, 5])

In [2]:
type(array)

numpy.ndarray

In [3]:
# Accessing elements of a NumPy array
print("First Element:", array[0])
print("Last Element:", array[-1])

First Element: 1
Last Element: 5


In [6]:
# Creating a 2D NumPy array
matrix = np.array([[1, 2], [4, 5], [7, 8]])
matrix

array([[1, 2],
       [4, 5],
       [7, 8]])

In [7]:
# Shape of the array
print("Shape of 1D Array:", array.shape)
print("Shape of 2D Array:", matrix.shape)

Shape of 1D Array: (5,)
Shape of 2D Array: (3, 2)


In [18]:
matrix[0]

array([1, 2])

In [19]:
# NumPy array operations
array_sum = np.sum(array)
array_mean = np.mean(array)
array_std_dev = np.std(array)
print("Array Sum:",array_sum)
print("Array Mean:",array_mean)
print("Array Standard Deviation:",array_std_dev)

Array Sum: 15
Array Mean: 3.0
Array Standard Deviation: 1.4142135623730951


In [24]:
# NumPy array operations on 2D arrays
matrix_sum = np.sum(matrix, axis=1)  # Sum along columns
matrix_sum

array([ 3,  9, 15])

In [26]:
# NumPy functions
array_square = np.square(array)
array_sqrt = np.sqrt(array)
array_exp = np.exp(array)
print("Array Square:",array_square)
print("Array Square Root:",array_sqrt)
print("Array Exponent:",array_exp)

Array Square: [ 1  4  9 16 25]
Array Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Array Exponent: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [27]:
sliced_array = array[1:4]  # Slices elements from index 1 to 3 (exclusive)
sliced_array

array([2, 3, 4])

In [29]:
# NumPy array reshaping
reshaped_array = array.reshape(1, 5)  # Reshapes the array to a 2D array with 1 row and 5 columns
reshaped_array

array([[1, 2, 3, 4, 5]])

In [30]:
# NumPy random functions
random_array = np.random.randint(1, 100, size=(3, 3))  # Generates a 3x3 random integer array between 1 and 100
random_array

array([[85, 68, 20],
       [84, 14, 85],
       [74,  9, 37]])

In [46]:
# NumPy array slicing
random_array[1:4]  # Slicing elements from index 1 to 3 (exclusive)

array([[84, 14, 85],
       [74,  9, 37]])

In [47]:
random_array[0:2, 1:3]  # Slicing sub-matrix from 2D array

array([[68, 20],
       [14, 85]])

In [31]:
# NumPy broadcasting
broadcasted_array = array + 10  # Adds 10 to each element of the array
broadcasted_array

array([11, 12, 13, 14, 15])

In [33]:
# NumPy linear algebra
matrix_inverse = np.linalg.inv(random_array)  # Computes the inverse of a matrix
matrix_inverse 

array([[-0.0013015 , -0.01230892,  0.02898077],
       [ 0.01676669,  0.00877327, -0.02921789],
       [-0.00147538,  0.02248381, -0.02382746]])

In [38]:
# NumPy boolean indexing
bool_array = random_array >50  # Creates a boolean array based on the condition
bool_array

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False, False]])

In [44]:
array = np.array([[1,6,1,5],
                 [4,6,4,8],
                 [6,8,6,1]])
# NumPy aggregate functions
unique_values = np.unique(array)  # Returns unique elements of the array
unique_values

array([1, 4, 5, 6, 8])

In [50]:
# NumPy statistical functions
array_median = np.median(random_array)  # Median of elements
array_median

68.0

In [51]:
array_percentile = np.percentile(random_array, 50)  # 50th percentile (median)
array_percentile

68.0